source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-seo-tag", "~> 2.9"
gem "jekyll-relative-links", "~> 0.8"
gem "minima", git: "https://github.com/jekyll/minima.git", ref: "4de322363fca5927e6f4012cb94f6dad69ab5e6c"
gem "openssl", "~> 4.0.2"
gem "logger"
